/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsSystemInfo {
  cpuTemp: number
  batteryPercentage: number
  batteryStatus: string
}
export declare function sayHello(): string
export declare function getSystemInfo(): JsSystemInfo
export declare function showNotification(title: string, message: string, urgency: string): boolean
